---
- block:
  - name: Check if awslogs is already installed
    stat: path=/var/awslogs/bin
    register: awslogs_bin_dir

  - include_tasks: install.yml
    when: not awslogs_bin_dir.stat.exists
  when: awslogs_install

- block:
  - name: Create logstream configuration
    template:
      src: awslogs_config.j2
      dest: /var/awslogs/etc/config/logs
      owner: root
      group: root
      mode: 0600
    notify: restart awslogs

  - name: Start and enable awslogs systemd service
    systemd:
      name: awslogs
      state: started
      enabled: yes
      daemon_reload: yes
  when: awslogs_manage

- name: Configure the http proxy
  lineinfile:
    dest: /var/awslogs/etc/proxy.conf
    regexp: "^HTTP_PROXY"
    line: "HTTP_PROXY={{ awslogs_http_proxy }}"
    state: present
    create: true
  notify: restart awslogs
  when: awslogs_http_proxy is defined

- name: Configure the https proxy
  lineinfile:
    dest: /var/awslogs/etc/proxy.conf
    regexp: "^HTTPS_PROXY"
    line: "HTTPS_PROXY={{ awslogs_http_proxy }}"
    state: present
    create: true
  notify: restart awslogs
  when: awslogs_https_proxy is defined
